services:
  fastapi:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./lv1:/app
    ports:
      - "8000:8000" #デバッグ用
    command: >
      sh -c "
        pip install -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --workers 16 --proxy-headers #自動起動
        #tail -f /dev/null #デバッグ
      "

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: calendar
    ports:
      - "5432:5432" #デバッグ用
    volumes:
      - ./db:/var/lib/postgresql/data