services:
  fastapi:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./fastapi:/app
    ports:
      - "8888:8888"
    command: >
      sh -c "
        pip install -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8888 --workers 16 --proxy-headers #自動起動
        #tail -f /dev/null #デバッグ
      "
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TZ=Asia/Tokyo

  scheduler:
    image: python:3.11-slim
    working_dir: /app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./scheduler:/app
    command: >
      sh -c "
        pip install -r requirements.txt &&
        python3 scheduler.py #自動起動
        #tail -f /dev/null #デバッグ
      "
    environment:
      - TZ=Asia/Tokyo

  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d calendar"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: calendar
      TZ: Asia/Tokyo
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5